import { Encryptor } from '@/security/Encryptor';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

describe('Encryptor', () => {
  beforeEach(() => {
    vi.resetModules();
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('should use PBKDF2 by default (when bcrypt is missing)', async () => {
    // Ensure bcrypt is not mocked/loaded
    vi.doMock('bcrypt', () => {
      throw new Error('Cannot find module');
    });

    const password = 'password123';
    const hash = await Encryptor.hash(password);

    expect(hash).toContain('pbkdf2$');
    expect(Encryptor.getAlgorithm()).toBe('pbkdf2');

    const isValid = await Encryptor.verify(password, hash);
    expect(isValid).toBe(true);

    const isInvalid = await Encryptor.verify('wrong', hash);
    expect(isInvalid).toBe(false);
  });

  it('should verify PBKDF2 hash correctly', async () => {
    const password = 'secret';
    // Manually create a PBKDF2 hash or use the one generated by hash()
    const hash = await Encryptor.hash(password);

    expect(await Encryptor.verify(password, hash)).toBe(true);
    expect(await Encryptor.verify('wrong', hash)).toBe(false);
  });

  it('should use bcrypt if available', async () => {
    const mockBcrypt = {
      hash: vi.fn().mockResolvedValue('$2b$10$mockhash'),
      compare: vi.fn().mockResolvedValue(true),
    };

    vi.doMock('bcrypt', () => ({ default: mockBcrypt }));

    // We need to reload the module to pick up the mock
    const { Encryptor: ReloadedEncryptor } = await import('@/security/Encryptor');

    const password = 'password123';
    const hash = await ReloadedEncryptor.hash(password);

    expect(hash).toBe('$2b$10$mockhash');
    expect(ReloadedEncryptor.getAlgorithm()).toBe('bcrypt');
    expect(mockBcrypt.hash).toHaveBeenCalled();
  });

  it('should verify bcrypt hash', async () => {
    const mockBcrypt = {
      hash: vi.fn(),
      compare: vi.fn().mockResolvedValue(true),
    };

    vi.doMock('bcrypt', () => ({ default: mockBcrypt }));

    const { Encryptor: ReloadedEncryptor } = await import('@/security/Encryptor');

    const password = 'password123';
    const hash = '$2b$10$existinghash';

    const isValid = await ReloadedEncryptor.verify(password, hash);
    expect(isValid).toBe(true);
    expect(mockBcrypt.compare).toHaveBeenCalledWith(password, hash);
  });

  it('should throw error if verifying bcrypt hash without bcrypt', async () => {
    vi.doMock('bcrypt', () => {
      throw new Error('Cannot find module');
    });

    const { Encryptor: ReloadedEncryptor } = await import('@/security/Encryptor');

    const hash = '$2b$10$existinghash';
    await expect(ReloadedEncryptor.verify('password', hash)).rejects.toThrow(
      'bcrypt not available to verify hash'
    );
  });
});
