import { Env } from '@zintrust/core';

export default {
  enabled: true,
  connection: 'sqlite',
  pruneAfterHours: Env.getInt('TRACE_PRUNE_HOURS', 72),
  ignoreRoutes: ['/trace', '/trace/api'],
  ignorePaths: ['/trace', '/trace/api', '.js', '.css'],
  captureCachePayloads: false,
  captureQueryBindings: false,
  contentDispatch: {
    driver: undefined,
    worker: {
      enabled: false,
      intervalMs: 0,
      maxDurationMs: 0,
      concurrency: 0,
    },
    queueName: '',
    enqueueTimeoutMs: 0,
  },
  watchers: {
    request: false,
    query: false,
    exception: false,
    log: false,
    job: false,
    cache: false,
    schedule: false,
    mail: false,
    auth: false,
    event: false,
    model: false,
    notification: false,
    redis: false,
    gate: false,
    middleware: false,
    command: false,
    batch: false,
    dump: false,
    view: false,
    clientRequest: false,
  },
};
